// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/*",
    "/favicon.png",
    "/robots.txt"
  ]
};

// node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "C:\\Users\\mario\\Projects\\horn553\\my-app\\.wrangler\\tmp\\pages-l9VHUT\\bundledWorker-0.7102892357912018.mjs";
import { isRoutingRuleMatch } from "C:\\Users\\mario\\Projects\\horn553\\my-app\\node_modules\\wrangler\\templates\\pages-dev-util.ts";
export * from "C:\\Users\\mario\\Projects\\horn553\\my-app\\.wrangler\\tmp\\pages-l9VHUT\\bundledWorker-0.7102892357912018.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        if (worker.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return worker.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=6o21xr2sgwo.js.map
